### PR TITLE
Embed default classifier (+ minor improvements)

### PR DESCRIPTION
**Pull request by ammario**
The main point of this change is embedding the default classifier so that library consumers don't have to worry about the classification file.

### CODE REVIEW

**Comment by ammario** [comment]
@hstove anything you'd like me to add to this PR to get it merged?

**Comment by hstove** [comment]
Hey! apologies for missing your initial PR. This is a real blast from the past - its cool to see a contribution many years later.

I have no need for this project or desire to maintain it - if you prefer to maintain it moving forward, I'm happy to archive this repo and point to yours.

**Comment by ammario** [comment]
Thanks for getting this in. It's a cool project, but I have no desire to maintain it as well.

**Comment by ammario** [comment]
If you wanna give me write access to `master`, I can fix https://github.com/hstove/gender/issues/1 real quick and maybe handle minor issues if they come up.

**Pull request merged**
